### ISSUE TITLE
How to use the trained model for inference?

### ISSUE THREAD

**Issue by GabrielLin** [hrukalive/WWW2020_paper2repo#1]
Could you please tell me help to use the trained model for inference a given paper for the recommendation? Thanks.

**Comment by hrukalive** [comment]
Hi, thanks for using the code. Because pytorch_lightning has undergone a big change in API, there may be some difficulties. But in general:
```python3
import torch
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import ModelCheckpoint
from p2r_module import P2rSystem

model = P2rSystem(hparams, data)
# Checkpoints saved under {}/{}/version_{}/checkpoints, with the best version named _ckpt_epoch_final.ckpt
checkpoint = ModelCheckpoint(filepath=CKPT_PATH, verbose=True, monitor='tng_loss', mode='min', save_best_only=True)
trainer = Trainer(checkpoint_callback=checkpoint)

trainer.eval()
_, _, ranks = trainer(LIST OF PAPERIDs, LIST OF LIST CONTAINING CORRESPONDING CANDIDATES FOR EACH PAPERID)
```
eg. for input, it is of this form (of course, these need to be LongTensor):
paperIDs: [42, 128]
repoIDs: [[1,3,5...], [3,6,9,...]]
You could put all possible repository IDs in for a full evaluation, but choosing only neighbors within some hops gives the best results.
The returned `ranks` is of the same dimension as repoIDs you passed in, tagging them with the ranks with respect to the paperID in that position.


In case pytorch_lightning has problems loading checkpoints, you may need to do things manually.
```python3
import torch
from models import P2r

p2r = P2r(hparams, data)
p2r.load_state_dict(torch.load(CKPT_PATH)['state_dict'])
p2r.eval()
_, _, ranks = p2r(LIST OF PAPERIDs, LIST OF LIST CONTAINING CORRESPONDING CANDIDATES FOR EACH PAPERID)
```

Thanks again.

**Comment by GabrielLin** [comment]
Dear @hrukalive , thanks for your reply. I will try it.
